package go.VO;

public class r_evaluationVO {
	
	String RESTAURANT_ID;
	String RESTAURANT_NAME;
	int TASTE_GOOD_TOTAL;
	int TASTE_BAD_TOTAL;
	int AMOUNT_GOOD_TOTAL;
	int AMOUNT_BAD_TOTAL;
	int SPEED_GOOD_TOTAL;
	int SPEED_BAD_TOTAL;
	int TOTAL_REPLE;
	int MASTER_REPLE;
	public r_evaluationVO(String rESTAURANT_ID, String rESTAURANT_NAME, int tASTE_GOOD_TOTAL, int tASTE_BAD_TOTAL,
			int aMOUNT_GOOD_TOTAL, int aMOUNT_BAD_TOTAL, int sPEED_GOOD_TOTAL, int sPEED_BAD_TOTAL, int tOTAL_REPLE,
			int mASTER_REPLE) {
		super();
		RESTAURANT_ID = rESTAURANT_ID;
		RESTAURANT_NAME = rESTAURANT_NAME;
		TASTE_GOOD_TOTAL = tASTE_GOOD_TOTAL;
		TASTE_BAD_TOTAL = tASTE_BAD_TOTAL;
		AMOUNT_GOOD_TOTAL = aMOUNT_GOOD_TOTAL;
		AMOUNT_BAD_TOTAL = aMOUNT_BAD_TOTAL;
		SPEED_GOOD_TOTAL = sPEED_GOOD_TOTAL;
		SPEED_BAD_TOTAL = sPEED_BAD_TOTAL;
		TOTAL_REPLE = tOTAL_REPLE;
		MASTER_REPLE = mASTER_REPLE;
	}
	public String getRESTAURANT_ID() {
		return RESTAURANT_ID;
	}
	public void setRESTAURANT_ID(String rESTAURANT_ID) {
		RESTAURANT_ID = rESTAURANT_ID;
	}
	public String getRESTAURANT_NAME() {
		return RESTAURANT_NAME;
	}
	public void setRESTAURANT_NAME(String rESTAURANT_NAME) {
		RESTAURANT_NAME = rESTAURANT_NAME;
	}
	public int getTASTE_GOOD_TOTAL() {
		return TASTE_GOOD_TOTAL;
	}
	public void setTASTE_GOOD_TOTAL(int tASTE_GOOD_TOTAL) {
		TASTE_GOOD_TOTAL = tASTE_GOOD_TOTAL;
	}
	public int getTASTE_BAD_TOTAL() {
		return TASTE_BAD_TOTAL;
	}
	public void setTASTE_BAD_TOTAL(int tASTE_BAD_TOTAL) {
		TASTE_BAD_TOTAL = tASTE_BAD_TOTAL;
	}
	public int getAMOUNT_GOOD_TOTAL() {
		return AMOUNT_GOOD_TOTAL;
	}
	public void setAMOUNT_GOOD_TOTAL(int aMOUNT_GOOD_TOTAL) {
		AMOUNT_GOOD_TOTAL = aMOUNT_GOOD_TOTAL;
	}
	public int getAMOUNT_BAD_TOTAL() {
		return AMOUNT_BAD_TOTAL;
	}
	public void setAMOUNT_BAD_TOTAL(int aMOUNT_BAD_TOTAL) {
		AMOUNT_BAD_TOTAL = aMOUNT_BAD_TOTAL;
	}
	public int getSPEED_GOOD_TOTAL() {
		return SPEED_GOOD_TOTAL;
	}
	public void setSPEED_GOOD_TOTAL(int sPEED_GOOD_TOTAL) {
		SPEED_GOOD_TOTAL = sPEED_GOOD_TOTAL;
	}
	public int getSPEED_BAD_TOTAL() {
		return SPEED_BAD_TOTAL;
	}
	public void setSPEED_BAD_TOTAL(int sPEED_BAD_TOTAL) {
		SPEED_BAD_TOTAL = sPEED_BAD_TOTAL;
	}
	public int getTOTAL_REPLE() {
		return TOTAL_REPLE;
	}
	public void setTOTAL_REPLE(int tOTAL_REPLE) {
		TOTAL_REPLE = tOTAL_REPLE;
	}
	public int getMASTER_REPLE() {
		return MASTER_REPLE;
	}
	public void setMASTER_REPLE(int mASTER_REPLE) {
		MASTER_REPLE = mASTER_REPLE;
	}
	@Override
	public String toString() {
		return "r_evaluationVO [RESTAURANT_ID=" + RESTAURANT_ID + ", RESTAURANT_NAME=" + RESTAURANT_NAME
				+ ", TASTE_GOOD_TOTAL=" + TASTE_GOOD_TOTAL + ", TASTE_BAD_TOTAL=" + TASTE_BAD_TOTAL
				+ ", AMOUNT_GOOD_TOTAL=" + AMOUNT_GOOD_TOTAL + ", AMOUNT_BAD_TOTAL=" + AMOUNT_BAD_TOTAL
				+ ", SPEED_GOOD_TOTAL=" + SPEED_GOOD_TOTAL + ", SPEED_BAD_TOTAL=" + SPEED_BAD_TOTAL + ", TOTAL_REPLE="
				+ TOTAL_REPLE + ", MASTER_REPLE=" + MASTER_REPLE + "]";
	}
	
	
	
	
	
}
